### PR TITLE
Update 03-upgrading-the-prisma-layer.mdx

### PR DESCRIPTION
**Pull request by hoogendjk**
change to remove prisma1 package and not the prisma package

## Describe this PR
changes to upgrade documentation

## Changes
change to remove prisma1 package instead of prisma

## What issue does this fix?
No issue available

### CODE REVIEW

**Review by Jolg42 — APPROVED** [review]
Looks good! Thanks!

**Comment by janpio** [comment]
This unfortunately only applies to users that upgrade to the `prisma1` package, not to the ones still using 1.x versions of `prisma`.

**Comment by Jolg42** [comment]
@janpio the page mentions `Note that the former prisma command for Prisma 1 has been renamed to prisma1. You can learn more about this here.` so it was confusing.

**Comment by janpio** [comment]
I do not remember what we actually did, but wasn't that "just" about the CLI command `prisma` and not the Npm package?

**Comment by Jolg42** [comment]
Indeed command and package of Prisma 1 were renamed.
- package `prisma` -> `prisma1` https://github.com/prisma/prisma1
- command `prisma` -> `prisma1` https://github.com/prisma/prisma1/blob/master/cli/packages/prisma-cli/package.json#L23

**Pull request merged**
