### PR TITLE
Move Data Proxy errors from "PDP > Data Proxy" to "Reference > Error message reference"

### LINKED ISSUE #3656: Docs: Consider merging the Data Proxy error codes with the Prisma Client errors reference
The Data Proxy error codes are essentially thrown by the Prisma Client. We have feedback that people are looking for the Data Proxy error codes in the Client errors reference and they're not finding it there.

### PR DESCRIPTION
**Pull request by zachtil**
## Describe this PR

It makes more sense to keep Data Proxy-related errors with the rest of the Error message reference material, under the main Reference section.

## Changes

* Remove the Errors section from the **PDP** > **Data Proxy** page
* Add the Data Proxy errors section to the **Reference** > **Error message reference** page
* Keep the style that already applies to the **Error message reference** page

## What issue does this fix?

Fixes #3656

### CODE REVIEW

**Review by tanberry — APPROVED** [review]
Looks good, thanks for doing this Zach. Question... did you use the script to generate this new content, to add it to the Reference docs? If not, and it was added manually, we will need to figure out how to get the script to generate it... or... remember to add it manually each time we regenerate the Reference dos. :-(

**Comment by tanberry** [comment]
@zachtil  looks like you will need to refresh this PR, or just manually manage the merge conflict that will occur because of the PR for updating the 4.5 errors on the Reference section, which @andrew-walford-prisma  just merged (https://github.com/prisma/docs/pull/3900)...

**Review by andrew-walford-prisma — COMMENTED** [review]
LGTM

**Comment by zachtil** [comment]
Thank you all for the reviews @tanberry @andrew-walford-prisma @janpio. Merging.

**Pull request merged**
